spring:
  datasource:
    username: root
    password: centerm123
    url: jdbc:mysql://localhost:3306/mptest?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 20
    maxActive: 100
    minIdle: 10
    maxWait: 60000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    validationQuery: SELECT 1
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 600000
    minEvictableIdleTimeMillis: 300000
    filters: stat,log4j,wall

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      #主键类型  0:"数据库ID自增",1:为空, 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID";
      id-type: AUTO

logging:
  file:
    path: logs